server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

[FORMATTER] [NITF] fixed double counter when no media is present

---

client/superdesk.config.js

bug was due to config typo only.  fixed.

SDNTB-339: Advanced search (NTB): services and subjects selected at once

---

server/requirements.txt

- allows tables in nitf output

update server core to 1.4.3

---

server/requirements.txt
server/settings.py

[INGEST] added option to skip IPTC codes processing during ingestion

---

client/package.json
server/requirements.txt

- fixing item comments notifications for users with `.` in username

update cores to 1.4.7

---

client/package.json
server/requirements.txt

Includes fixes for:
- edit content profiles for custom fields
- signoff update on user email update

chore(cores): Update superdesk cores for NTB

---

server/ntb/macros/valuta.py

I have removed the date in the xpath and replaced it with specific choice of node. First node is today, second node is the day before today with data (as in either Monday or Friday).
I see I have done one thing wrong, by changing the first doc.findall to doc.find. I will do a second pull request if OK.

Committing changes to valuta.py (currency table)

---

server/ntb/macros/valuta.py

I found a typo on line 72. This will correct. The macro also fails.

Corrected typo

---

server/ntb/macros/valuta.py

I have also renamed the variables so they are aligned with Python style.

Changed the way it gets the data from the XML

---

server/ntb/macros/valuta.py

I changed the number of days to go back to Monday. I also adjusted the code so the yesterday date uses the value set and not creating (sort of) new values based on new object.

Making sure we are on Monday

---

server/ntb/macros/valuta.py

If you want to test against other days of the week, comment out line 100 and comment in line 101

After testing the Monday "bug", this is the final version.

---

server/ntb/macros/valuta.py

I have removed the date() from the object that is sent into the main function. I believe this is the reason as the test one did not send the date() part.

removed date from ntb_currency_macro() today_date.

---

server/ntb/macros/valuta.py

Correcting . (dots) in currencies to , (comma)

Correcting NOK becomes EUR

---

server/ntb/macros/valuta.py

Noticed that the journalist wanted it to say Euro and not EURO. I have corrected the definition in the list/array

Corrected EURO to Euro so it aligns with the rest of the text

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

it was putting following p tags into the previous one containing
br tag.

fix(nitf): fix output when there is <br>

---

server/ntb/macros/abstract_populator.py
server/ntb/macros/extract_html.py
server/ntb/macros/extract_html_tests.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/io/feed_parsers/nitf_tests.py
server/ntb/tests/io/fixtures/nitf_test.xml
server/requirements.txt

replaced BeautifulSoup by lxml, following changes in superdesk-core

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

also improve count for pubdata's item-length by removing line feeds
SDNTB-388

[FORMATTER] [NITF] replace &nbsp; by normal space

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

[FORMATTER] [NITF] fixed crash when an association data is None

---

client/package.json
server/data/vocabularies.json
server/ntb/io/__init__.py
server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py
server/requirements.txt
server/settings.py

This commit add Wufoo feed parser (using its API) working on Personalia form set up for
NTB.
added wufoo in subscriber types
SDNTB-377

wufoo feed parser

---

server/ntb/io/feed_parsers/__init__.py
server/requirements.txt

This webhook only work if a provider named "Personalia" exists
SDNTB-378

added Personalia webhook

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py

- months are in lowercase
- address ending changed
- replace '\n' by <br/> in biography
- wrap body_html in a <p> element
SDNTB-397

[FEED PARSER][WUFOO] some adjustments

---

client/superdesk.config.js

it is renamed in 1.7, for now keep both
https://github.com/superdesk/superdesk-client-core/pull/1404

fix scanpixSearchShortcut config

---

server/settings.py

removed app.group

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py

[FEED_PARSER] [WUFOO] added missing coma

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py

set sign_off to "personalia@ntb.no"
SDNTB-430

[FEED PARSER] [WUFOO] set sign_off

---

server/data/vocabularies.json
server/data_updates/00000_20170614-125234_vocabularies.py

SDNTB-428
works with https://github.com/superdesk/superdesk-client-core/pull/1678

put schema for genre and category into vocabularies

---

server/ntb/io/feed_parsers/ntb_nitf.py

xpath expression for metadata was bad, resulting in tests failing.
SDNTB-432

[FEED PARSER] [NTB NITF] fixed by xpath in mapping

---

client/package.json
client/superdesk.config.js

update tansa language codes

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

fix(nitf): handle rewrite sequence set to none

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

fix(nitf): allow null language in output

---

server/data/vocabularies.json
server/ntb/publish/__init__.py
server/ntb/publish/ntb_nitf.py
server/ntb/publish/ntb_nitf_multifile.py
server/ntb/publish/ntb_nitf_multiservice.py
server/ntb/tests/publish/ntb_nitf_legacy_test.py

so there are 3 ntb nitf formatters:
- NTB NITF 1.0 - old one - creates 1 file with first service only
- NTB NITF Multi Service - default - creates 1 file with all services
- NTB NITF Multi File - creates 1 file per service
SDNTB-456

re-introduce ntb nitf formatter

---

server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/afp_newsml.py
server/ntb/io/feed_parsers/utils.py
server/ntb/tests/io/feed_parsers/__init__.py
server/ntb/tests/io/feed_parsers/afp_newsml_tests.py
server/ntb/tests/io/feed_parsers/nitf_tests.py
server/ntb/tests/io/fixtures/afp.xml

feat(afp): add ntb afp newsml parser

---

server/ntb/io/feed_parsers/afp_newsml.py
server/ntb/io/feed_parsers/utils.py
server/ntb/tests/io/feed_parsers/afp_newsml_tests.py

fix(ingest): populate service when ingesting AFP NewsML

---

server/ntb/io/feed_parsers/stt_newsml.py
server/ntb/tests/io/feed_parsers/__init__.py
server/ntb/tests/io/feed_parsers/stt_newsml_test.py
server/ntb/tests/io/fixtures/stt_newsml_sport_test.xml
server/ntb/tests/io/fixtures/stt_newsml_test.xml
server/requirements.txt
server/settings.py

this patch add a parser for the STT variant of NewsML
SDNTB-462

[FEED PARSER] NEWSML (STT)

---

server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/dpa_newsml.py
server/ntb/io/feed_parsers/stt_newsml.py
server/ntb/tests/io/feed_parsers/dpa_newsml_test.py
server/ntb/tests/io/fixtures/dpa_newsml_test.xml
server/requirements.txt

[FEED PARSER] DPA NewsML feed parser

---

server/ntb/io/feed_parsers/tt_newsml.py
server/ntb/tests/io/feed_parsers/tt_newsml_test.py
server/ntb/tests/io/fixtures/tt_newsml_test.xml

this patch implement TT variant of NewsML
SDNTB-463

[WIP] [FEED PARSER] [TT] TT NewsML feed parsed

---

server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/ritzau.py
server/ntb/tests/io/feed_parsers/__init__.py
server/ntb/tests/io/feed_parsers/ritzau_test.py
server/ntb/tests/io/fixtures/ritzau.xml
server/ntb/tests/io/fixtures/ritzau_2.xml
server/requirements.txt

[INGEST] [FEED PARSER] added NTB version of Ritzau feed parser

---

server/ntb/io/feed_parsers/__init__.py

TT feed parsed was not registered correctly
SDNTB-463

[FEED PARSER [TT] fixed missing module call

---

server/settings.py

set publish queue expiry to 30d

---

server/ntb/io/feed_parsers/ntb_nifs.py
server/ntb/tests/io/feed_parsers/nifs_events_test.py
server/settings.py

- added "service" (anpa_category) "subject" and "calendars" metadata.
- retrieve labels from vocabularies, according to set qcodes.
SDNTB-496

[FEED PARSER][NTB NIFS] metadata update

---

server/ntb/io/feed_parsers/ntb_nifs.py

metadata initialization was failing because vocabularies are not
accessible yet when __init__ is called.
This patch fixes this by initializing metadata on first parsing, and
then using cached values.
SDNTB-496

[FEED PARSER] [NTB NIFS] fixed metadata initialization

---

client/package.json
server/ntb/scanpix/scanpix_datalayer.py

[SCANPIX] use resource as provider name on externalProviderError

---

server/ntb/io/feed_parsers/tt_newsml.py
server/ntb/tests/io/feed_parsers/tt_newsml_test.py

set sport category for other sport services

---

server/data/vocabularies.json
server/data_updates/00014_20181026-144228_vocabularies.py

add schema_field so category is available in planning

---

client/package.json
server/data/planning_types.json
server/requirements.txt

and update plannig to version which supports it
SDNTB-527

configure planning list fields

---

client/package.json
server/requirements.txt

core to 1.26, planning to latest

update cores & planning

---

server/settings.py

update export as article template

---

server/data/vocabularies.json

fix empty content profile editor

---

server/data/vocabularies.json

Reverts superdesk/superdesk-ntb#287

Revert "fix empty content profile editor"

---

server/data/vocabularies.json

schema_field subject can be only used once
SDNTB-550

fix content profile editing

---

client/package.json
server/data/planning_types.json
server/requirements.txt

SDNTB-550 SDESK-3485
uses https://github.com/superdesk/superdesk-planning/pull/1116

configure custom cvs editor in planning

---

server/data/vocabularies.json
server/data_updates/00016_20190123-155821_vocabularies.py
server/ntb/publish/ntb_nitf.py

it must be unset on ntb-next, empty string doesn't work really
SDNTB-550

fix wrong schema field in vocabulary using migrations

---

server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/solita.py
server/ntb/tests/io/feed_parsers/solita_test.py
server/ntb/tests/io/fixtures/solita_1.xml
server/ntb/tests/io/fixtures/solita_2.xml
server/ntb/tests/io/fixtures/solita_3.xml

implemented parser for Solita files.
SDNTB-561

[FEED PARSER] Solita

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py

- it's in user timezone not utc
SDNTB-565

fix(wufoo): fix timestamps

---

server/data/planning_types.json

update planning schema

---

server/ntb/io/feeding_services/newsworthy.py
server/ntb/tests/io/feeding_services/newsworthy_test.py
server/settings.py

[FEEDING SERVICE] implementation of Newsworthy Feeding Service

---

server/ntb/io/feed_parsers/solita.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/io/feed_parsers/solita_test.py
server/ntb/tests/publish/ntb_nitf_test.py

- changed headline (use only title)
- publisher name is put in extra data, and use in NTB NITF
- fixed handling of multiple images
SDNTB-574

[FEED PARSER][FORMATTER][SOLITA][NTB NITF] misc changes and fixes

---

server/ntb/io/feed_parsers/solita.py
server/ntb/tests/io/feed_parsers/solita_test.py
server/ntb/tests/io/fixtures/solita_2.xml

- kontakter header is now only shown once for all contacts
- changed ednote text
- changed text for last body paragraph
SDNTB-574

[FEED PARSER][SOLITA] text changes

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

[FORMATTER][NTB NITF] Added "NTBNewsValue" metadata (priority)

---

.travis.yml
Dockerfile
server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/solita_se.py
server/ntb/tests/io/feed_parsers/__init__.py
server/ntb/tests/io/feed_parsers/solita_se_test.py
server/ntb/tests/io/fixtures/solita_se_1.xml

[FEED PARSER] Solita Stock Exchange feed parser

---

server/ntb/io/feed_parsers/solita.py
server/ntb/tests/io/feed_parsers/solita_test.py

[FEED PARSER][SOLITA] added a colon after "Se saken i sin helhe" in body

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py

[FEED PARSER][WUFOO] don't show country name is it is "Norge" or "Noreg"

---

server/ntb/io/feed_parsers/solita_se.py
server/ntb/tests/io/feed_parsers/solita_se_test.py

[FEED PARSER] SOLITA SE

---

server/ntb/ping_scanpix.py
server/ntb/scanpix/scanpix_datalayer.py
server/ntb/tests/fixtures/published_item.json
server/ntb/tests/ping_scanpix_test.py

fetch original image from scanpix when item is published

---

client/superdesk.config.js
client/yarn.lock

SDNTB-545
It requires https://github.com/superdesk/superdesk-client-core/pull/2980

Add custom sort to scheduled output

---

server/data/vocabularies.json
server/ntb/publish/ntb_nitf.py
server/ntb/publish/ntb_nitf_multiservice.py
server/ntb/tests/publish/ntb_nitf_multiservice_test.py

add new formatter which returns original href for scanpix

---

server/ntb/io/feed_parsers/solita_se.py
server/ntb/tests/io/feed_parsers/solita_se_test.py

[FEED PARSER][SOLITA SE] fixed bad attribute in <a> element

---

client/package.json

Update client core to develop branch

---

server/requirements.txt

Use develop branch instead of master for superdesk-core

Use develop branch instead of master

---

server/data/vocabularies.json

Change Place CV to "manageable"

Change Place CV to "manageable"

---

client/superdesk.config.js

to highlight search results in the results page

Added elasticHighlight: true

---

client/package.json
client/superdesk.config.js
server/requirements.txt

use stable cores

---

server/ntb/ping_scanpix.py
server/ntb/tests/ping_scanpix_test.py

add service to ping payload

---

server/ntb/io/feed_parsers/afp_newsml.py
server/ntb/tests/io/feed_parsers/afp_newsml_tests.py
server/ntb/tests/io/fixtures/afp.xml

parse ednote in afp newsml

---

server/settings.py

Added INGEST_OLD_CONTENT_MINUTES

---

server/ntb/__init__.py
server/ntb/content_api_rss.py
server/ntb/tests/content_api_rss_test.py

fix rss content for empty body

---

client/ntb/views/login-modal.html
client/package.json
server/requirements.txt
server/settings.py

and make standard login configurable via env variable

use cores 1.32

---

server/ntb/io/feed_parsers/ntb_tt_ninjs.py

SDNTB:638 Update tt ninjs parser for ntb

---

server/data/vocabularies.json

new Topics vocabulary based on IPTC media topics in Norwegian with mapping to wikidata and IPTC subject codes.

Add "topics" [SDNTB-636]

---

server/manage.py
server/ntb/commands/__init__.py
server/ntb/commands/migrate_topics.py

it's called `ntb:migrate_topics`
SDNTB-644

implement manage command to populate topics

---

server/ntb/ping_scanpix.py

use hash of the scanpix id when pushing it to amazon

---

server/data/vocabularies.json

enable imatrics formatter

---

client/ntb/index.js
client/package-lock.json
client/package.json
server/data/vocabularies.json
server/manage.py
server/requirements.txt
server/settings.py

setup auto tagging on ntb branch

---

server/ntb/macros/set_desk_metadata_macro.py
server/ntb/tests/macros/set_desk_metadata_macro_test.py

implement macro to set metadata based on desk template

---

client/superdesk.config.js

updated config for sorting of the iMatrics fields  (client core 2.2.1)

update iMatrics config

---

client/superdesk.config.js
server/data/config.json

move startingDay option from js file to database

---

client/package-lock.json
server/ntb/publish/ntb_nitf.py
server/ntb/publish/ntb_nitf_multiservice.py
server/ntb/tests/publish/ntb_nitf_multiservice_test.py
server/ntb/tests/publish/ntb_nitf_test.py

- populate entity id using wikidata
- avoid slugline in key list for NTB NITF 2
- use topics for subject when available, fallback to subject_custom
SDNTB-647

fix nitf imatrics handling

---

server/ntb/publish/ntb_nitf.py

avoid overriding topics subject

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/mediatopics_to_subject_mapping_test.py
server/ntb/tests/mock.py

which does not work with different schemas
and same codes
SDNTB-740

fix nitf populate parent

---

server/app.py
server/ntb/io/feed_parsers/solita_se.py
server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/solita_se_test.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py
server/requirements.txt
server/settings.py

fix solita/wufoo ingest defaults

---

server/ntb/macros/imatrics.py

implement iMatrics macro

---

server/data/vocabularies.json

update mediatopics CV

---

server/ntb/publish/ntb_ninjs.py
server/ntb/publish/ntb_nitf.py
server/ntb/publish/utils.py
server/ntb/tests/publish/ntb_ninjs_test.py

add missing fields to NTB NINJS output

---

server/ntb/publish/ntb_ninjs.py
server/ntb/tests/publish/ntb_ninjs_test.py

fix missing fields in ninjs 2.0

---

server/ntb/publish/ntb_ninjs.py
server/ntb/tests/publish/ntb_ninjs_test.py

there might be empty scheme in images
SDNTB-806

fix ntb ninjs associated image formatting

---

server/ntb/commands/__init__.py
server/ntb/commands/fix_events_moment_timezone_2023.py

implement script to fix event times being off due to timezone data

---

server/ntb/publish/ntb_ninjs.py
server/ntb/publish/ntb_nitf.py
server/ntb/publish/utils.py
server/ntb/tests/publish/ntb_ninjs_test.py

so there is similar logic in both
SDNTB-811

refactor html formatting for nitf/ninjs

---

server/ntb/publish/ntb_event.py
server/ntb/publish/ntb_nitf.py
server/ntb/publish/ntb_nitf_multifile.py
server/ntb/publish/ntb_nitf_multiservice.py

add names to output formatters

---

server/ntb/tests/publish/fixtures/text-item-with-table.json
server/ntb/tests/publish/ntb_ninjs_test.py
server/settings.py

allow tables in the NINJS output

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_ninjs_test.py
server/ntb/tests/publish/ntb_nitf_test.py

fix formatter for places with missing wikidata id

---

server/ntb/publish/ntb_ninjs.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

avoid using place qcode in nitf

---

server/data/vocabularies.json

update existing media topics
