superdesk/superdesk-ntb

server/ntb/io/feed_parsers/ntb_nitf.py
server/ntb/tests/io/feed_parsers/nitf_tests.py
server/ntb/tests/io/fixtures/nitf_test.xml
server/settings.py

subjects parsing was using defaut nitf parser (from superdesk-core)
which is not adapted to NTB behaviour.
This commit change this to have a simple qcode/name copying from the
source data.
SDNTB-344

[NITF] [PARSER] changed subjects parsing behaviour

---

server/settings.py

a forced time-zone in settings avoid depending on local timezone in
backend, and avoid issues like SDNTB-347 .

Forced time-zone in backend to Europe/Oslo

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

according to SDNTB-352, a unique ID is now needed for all the versions
(original and updated) of the published items.
This commit do this by using family_id.

[FORMATTER] [NITF] changed doc_id and NTBID format

---

server/data/content_types.json

- remove field Priority from all 3 content profiles
- rename HAST content profile to PUSH
- set 100 character limit (maxlength) for Headline for all 3 CPs (instead of 64)
- set 200 chars maxlength for abstract field for Normal and Spesial (instead of 160)
- add  body_footer field to Spesial, it should have no default value, position/order in the editor: 17
SDNTB-353

update content types

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

unbound namespaces were already removed from elements, this commit
improve this by removing them from attributes too.
This method use regex and may not be the most robust, the use of lxml
would simplify it, so https://dev.sourcefabric.org/browse/SDNTB-354 has
been created.
fix SDNTB-351

[FORMATTER] [NITF] remove unbound namespace from attributes

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

featuremedia can sometimes be None (video added then removed?), which
was not expected in NITF formatter, resulting in a crash.
This commit fix this.
SDNTB-355

[FORMATTER] [NITF] fix crash when featuremedia (or featureimage) is None

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

if blank text is not removed, pretty print will not work as expected
because it can't know if blank text is significant or not. Using
remove_blank_text when parsing body_html should fix the problem.
cf. http://lxml.de/FAQ.html#why-doesn-t-the-pretty-print-option-reformat-my-xml-output
SDNTB-328

[FORMATTER] [NITF] remove blank text on body_html parsing

---

server/ntb/macros/valuta.py

Corrected so the calculation finds the yesterday euro-value and passes that to the generate_row function.
This shall correct the bug where we are using the wrong value (today) to calculate yesterday value for currencies.

bug-fix: Calculation of yesterday values.

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

strip_invalid_chars can be called with None if a value exists but is
None. This commit fixes this by using empty string in this case.
SDNTB-396

[FORMATTER] [NITF] fixed crash when description_text is None

---

server/ntb/publish/ntb_nitf.py
server/requirements.txt

Following changes in superdesk-core, HTML2NITF is no more a class
attribute but it is an instance one. deepcopy is not needed anymore,
neither is staticmethod decorator for p_filter.
SDNTB-398

[FORMATTER] [NITF] minor changes for HTML2NITF

---

client/package.json
server/ntb/scanpix/scanpix_datalayer.py

subscription option has been removed from UI, so there is no need to get
if from query anymore.
the ntbtema hack is kept, so the behaviours doesn't change

[SEARCH PROVIDER] [SCANPIX] don't get subscription from query anymore

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

NTB NITF formatter was raising an exception when body_html was None or
not set, this commit fixes it.
SDNTB-420

[FORMATTER] [NITF] fix exception when body_html is None

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py

<br/> was escaped due to misplaced parenthesis, this commit fixes it.
SDNTB-418

[FEED PARSER] [WUFOO] fixed bad escaping of <br/> element

---

server/manage.py

- there are no changes needed, so avoid any downtime when updating

disable elastic settings update when running manage.py

---

server/ntb/io/feed_parsers/stt_newsml.py

NTB variant of STT parser was not correctly calling parent parse()
method, this patch fixes it.
SDNTB-482

[FEED PARSER][STT] fixed call of parent parse() method

---

server/ntb/io/feed_parsers/ntb_nifs.py
server/ntb/tests/io/feed_parsers/nifs_events_test.py

Python 3.6 accept to load json from bytes if they are encoded in UTF-8,
but Python 3.5 doesn't, resulting in crash. This patch make NTB NIFS feed
parser compatible with Python 3.5
SDNTB-480

[FEED PARSER] [NTF NIFS] decode data on reception

---

server/ntb/io/feed_parsers/wufoo.py
server/ntb/macros/nob_NO_publish_macro.py
server/ntb/macros/nob_NO_translate_macro.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py
server/requirements.txt
server/setup.cfg

if a field is missing, an empty string is used instead.
In the case of "birth date", a warning is printed and current date is
used.
This patch also fixes code style in few files and disable W503 warning
for flake8, which is not valid anymore (PEP 8 has changed on this point).
SDNTB-509

[FEED PARSER] [WUFOO] Don't fail on missing field

---

server/ntb/io/feed_parsers/ntb_nifs.py
server/ntb/tests/io/feed_parsers/nifs_events_test.py

item['dates']['tz] was using None while the schema uses a non nullable
string.
This patch fixes it by using empty string instead.
SDNTB-557

[FEED PARSER] [NIFS] Fixed use of None in item['dates']['tz']

---

docker/common.yml

Named container ar easier to use when developing. This patch name them
in the same way as in superdesk/superdesk

[DOCKER] use names for containers

---

server/ntb/io/feed_parsers/solita.py
server/ntb/tests/io/feed_parsers/__init__.py
server/ntb/tests/io/feed_parsers/solita_test.py

guid is now build using `provider_id` and `release_id`, this way it is
unique per provider, and avoid ingesting twice the same item.
added missing "genre"
use level heading for contacts and documents.
SDNTB-561

[FEED PARSER] [SOLITA] added missing genre + some improvments

---

server/ntb/io/feed_parsers/solita.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/io/feed_parsers/solita_test.py
server/ntb/tests/publish/ntb_nitf_test.py

image are added to associations and embed marquers are set so formatter
(notably NTB NITF) can render those images.
SDNTB-566

[FEED PARSER][SOLITA]add images to association + embedded marquer

---

client/superdesk.config.js

SDNTB-545
This will sort the stage by default, without user intervention.
User can still override this in the UI with the dropdown.
It needs https://github.com/superdesk/superdesk-client-core/pull/2994

Sort scheduled output by scheduled time

---

server/data/planning_export_templates.json
server/templates/planning_group_by_date.html

SDNTB-585
Each items has the same format than before but they're all grouped by date
Each group has a subheading: `Day of week (in Norwegian) day/month`

New planning export template: Group by date

---

server/ntb/ping_scanpix.py
server/ntb/tests/ping_scanpix_test.py

it would only set original rendition when the image wasn't
uploaded in superdesk, but all following calls with same
picture were noops
SDNTB-608 SDNTB-609

fix scanpix links

---

server/features/environment.py
server/features/ingest_ntb_events_api.feature
server/features/ingest_ntb_events_file.feature
server/features/steps/steps.py
server/ntb/io/feed_parsers/__init__.py
server/ntb/io/feed_parsers/ntb_event_xml.py
server/ntb/io/feed_parsers/ntb_nifs.py
server/ntb/io/feed_parsers/ritzau.py
server/ntb/macros/en_to_no_macro.py
server/ntb/macros/extract_html.py
server/ntb/macros/nb_NO_to_nn_NO_metadata_macro.py
server/ntb/macros/nob_NO_publish_macro.py
server/ntb/macros/nob_NO_translate_macro.py
server/ntb/macros/npk_metadata.py
server/ntb/macros/valuta.py
server/ntb/publish/__init__.py
server/ntb/publish/ntb_event.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/io/feed_parsers/ntb_event_xml_tests.py
server/ntb/tests/io/feed_parsers/solita_test.py
server/ntb/tests/io/feed_parsers/wufoo_tests.py
server/ntb/tests/io/feeding_services/event_email_service_tests.py
server/ntb/tests/io/feeding_services/event_http_service_tests.py
server/ntb/tests/io/feeding_services/ntb_event_file_test.py
server/ntb/tests/io/fixtures/ntb_event.xml
server/ntb/tests/io/fixtures/ntb_events_file/ntb_event_xml
server/ntb/tests/publish/ntb_event_test.py
server/ntb/tests/publish/ntb_nitf_test.py
server/setup.cfg

This PR depends on https://github.com/superdesk/superdesk-planning/pull/1363 and until PR for a planning component is not merged build will fail.
There is another PR for testing all together https://github.com/superdesk/superdesk-ntb/pull/345
NOTE: I was able to ingest and output events on a test instance https://ntbpr-345.test.superdesk.org

Move NTB related code from planning component

---

client/superdesk.config.js

NTB requested some changes to the Norwegian translation but they'd only work for NTB (like NTB-planer for a Planning item). We'll try with language override.

Updated list view, language override

---

.travis.yml
server/ntb/macros/__init__.py
server/ntb/macros/npk_metadata.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/io/feeding_services/event_email_service_tests.py
server/ntb/tests/publish/ntb_nitf_legacy_test.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt
server/setup.cfg

SDNTB-620 
SDNTB-621
- Use an original item's guid/_id to create an NTBID (NITF) when an update is published.
- Make a translation link between items in **NPKSisteNytt Metadata Macro** 
⚠️ This PR requires **superdesk-core v1.33** (it's not released at the time of PR), that's why **develop** branch is used.

SDNTB-620 A duplicate published in NTB NITF format has the same NTBID as the original story

---

server/ntb/io/feed_parsers/afp_newsml.py
server/ntb/tests/io/feed_parsers/afp_newsml_tests.py
server/ntb/tests/io/fixtures/afp_no_headline_2.xml

parsing of body could fail when 2 elements where on the same line.
fix SDNTB-627

[FEED PARSEDER][AFP NEWSML] fixed body parsing when there is no headline

---

server/ntb/publish/ntb_nitf.py
server/ntb/publish/ntb_nitf_multiservice.py
server/ntb/tests/publish/ntb_event_test.py
server/ntb/tests/publish/ntb_nitf_test.py

New Requirement:
- if the "place_custom" CV is part of the content profile, we'd use it.
- if the "place_custom" is not in the content profile, the place field will be populated from the iMatrics integration from the "place"

Add the place in Imatrics entities.

---

server/settings.py

- should be 10s by default
- use env var to be able to tweak it
SDNTB-797

change FTP_TIMEOUT timeout config

---

server/ntb/publish/ntb_ninjs.py
server/ntb/tests/publish/ntb_ninjs_test.py

add byline to ntb ninjs 2 output
